### ISSUE TITLE
Obtain version from a single source

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#116]
Let's create a single place where the version for the application is derived from during packaging.

Either create a package-time script or a runtime reader of the `pyproject.toml` or something else, and prevent us from having to remember to update this in multiple places.

Bonus points if we can stop worrying about versions altogether and let the CI system generate it for us, updating it in a reasonable manner with each release.

(From comments in #111)

**Comment by eniklas** [comment]
Fixed in https://github.com/eniklas/gamatrix/pull/121.
