### ISSUE TITLE
Add column for save file location

### ISSUE THREAD

**Issue by tim-sebring** [eniklas/gamatrix-gog#124]
While it's not necessarily used in the lan party management of determining who has what game [installed], sometimes it's handy to know where a particular game as a save file located. For example, I have a problem with my Fallout 4 install (keep getting disk error) so I wanted to back up my saves before uninstalling. I had to search to find where they were located.

**Comment by eniklas** [comment]
I'm almost positive the save location for a game is not in the GOG DB. Judging from the UI, the install location is there for GOG games, but even in that case, that's not necessarily where the save file is. You could use the [comment field](https://github.com/eniklas/gamatrix-configs/blob/9b2704e7f37d0b9c921e8a4492fd3d25a9030539/config.yaml#L85) to include the save file location if you want. That probably won't look great in the table though, so I'd recommend just putting it in the [spreadsheet](https://github.com/eniklas/gamatrix-configs/blob/9b2704e7f37d0b9c921e8a4492fd3d25a9030539/config.yaml#L80) (which is a lot easier to maintain anyway).

**Comment by tim-sebring** [comment]
Saul Goodman, it was just a thought. I've had to search the web times over the years to find a the location for a particular game. Feel free to close the issue eh!
