### ISSUE TITLE
Player title bar at top

### ISSUE THREAD

**Issue by tim-sebring** [eniklas/gamatrix-gog#15]
Would be cool for the grid to have the player headers at the top remain up top when scrolling, so you don't have to scroll back up to remember who is in what column.

**Comment by eniklas** [comment]
Beauty idea, I've found that annoying too when the title bar scrolls off the top. I've thought about repeating the bar every so many rows, or just putting the usernames in the cells every so often (I've tried putting them in every row but it's distracting). Looks like a sticky bar [would require JavaScript](https://www.w3schools.com/howto/howto_js_sticky_header.asp), which I'm not necessarily opposed to.

**Comment by eniklas** [comment]
Another way with pure CSS: https://stackoverflow.com/questions/15894997/how-to-make-the-title-bar-fixed

**Comment by eniklas** [comment]
The CSS/JavaScript route was a little hairy, so I got out cheap by putting the usernames in the cells every 25 lines in 71c7d45. @tim-sebring take a look and let me know what you think.
