### ISSUE TITLE
Allow notes & attachments for each game

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#20]
Would be great to keep notes from our LAN parties about each game (great maps to play, race courses, etc...) as well as attachments (3rd party mods, files that explain setup/how to play that sort of thing) and links.

**Comment by eniklas** [comment]
@derek-keeler was thinking about this recently; currently you can add any text you like to the `comment` for the title in the config yaml, but if you add a lot of text it will quickly make the table look disgusting. How about a `url` for the title? If present, we can make the title a link to that URL, and that can point to whatever (Google doc, etc.).

**Comment by eniklas** [comment]
`url` metadata key added in b4d0ed1.
