### ISSUE TITLE
Add dockerfile for Windows

### ISSUE THREAD

**Issue by eniklas** [eniklas/gamatrix-gog#23]

**Comment by d3r3kk** [comment]
Windows-based docker image? Why?

**Comment by eniklas** [comment]
Not a Windows-based image, just a [Dockerfile](https://github.com/eniklas/gamatrix-gog/blob/master/Dockerfile) that works with Windows paths and commands. I'm not even sure anything needs to be changed, I just haven't tried building this on Windows and @Graybriel was having issues.

**Comment by d3r3kk** [comment]
Ah gotcha! Will give it a go and report back.

**Comment by derek-keeler** [comment]
Closing this as I think I've proven it out with Windows paths in the `config-sample-win.yaml` and in the `README.md` docs.
