### ISSUE TITLE
Consider renaming gamatrix-gog.py to a pythonic filename

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#38]
**Consider renaming this script**

See https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them/762693

Otherwise, to properly test (or import our project into something else) we
will need to do funky stuff like this:

```python
gog = __import__("gamatrix-gog")

...

gog.build_config(args)

```

**Comment by eniklas** [comment]
So basically the `-` is the only issue? Are you planning to do any more development on gamatrix? If not, maybe we should just rename this project to gamatrix, or pick another name while we're at it. I never loved gamatrix-gog; that was chosen on day 1 as I thought I might merge it with gamatrix.

**Comment by derek-keeler** [comment]
@eniklas I've archived my old-n-busted `gamatrix` and renamed it to remove any confusion between all its user.

Please rename this repo to just `gamatrix` or something far sexier and then I can make some naming &  layout adjustments if you like.

**Comment by eniklas** [comment]
Done in https://github.com/eniklas/gamatrix/pull/102. Thanks @derek-keeler!
