### ISSUE TITLE
Handle scenario were we do not get a gamer db service access token

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#42]
The app can continue along without the db service's API token, handle the case where one is not available, log it, and continue processing without the data that service would grant us. 

https://github.com/eniklas/gamatrix-gog/blob/c4a3fd89da20919ee4eadc143e8ddffd850ab77f/gamatrix-gog.py#L359

**Comment by eniklas** [comment]
Done in https://github.com/eniklas/gamatrix-gog/pull/54.
