### ISSUE TITLE
Organize images to allow for web development in the static/ folder

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#96]
I'd like to organize how images are kept in our repo a bit. One reason is to make it a bit clearer about the purpose of various images (the `images/` folder in the root is not used for anything but documentation, for instance, and not used in production) as well as make the `.gitignore` file slightly simpler.

A side benefit of this cleanup makes us of the `static/` folder for web dev a bit more straightforward as well.

**Comment by derek-keeler** [comment]
❗ **Note** ❗ 

Such a cleanup would have an effect on the configuration of any running services at the moment (not particularly destructive, but definitely annoying for the admin).

**Comment by eniklas** [comment]
@derek-keeler closing this issue, we forgot when we merged the PR.
